source 'https://rubygems.org'

gem 'ruby-ldap'
gem 'rake'
gem 'wunderbar'
# later versions of ruby2js don't work with agenda
gem 'ruby2js', '3.6.1'
gem 'sinatra', '~> 2.0'
gem 'nokogumbo'
gem 'execjs'
gem 'listen'
gem 'activesupport'
gem 'mail'
gem 'erubis'
gem 'mustache'

gem 'websocket-eventmachine-server'
gem 'websocket-eventmachine-client'
gem 'concurrent-ruby'

gem 'rubyXL'

gem 'chronic'

group :test do
  gem 'rspec'
  gem 'puma'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'passenger'
end
