source 'https://rubygems.org'

gem 'mail'
gem 'rake'
gem 'wunderbar'
gem 'ruby2js'
gem 'ruby-ldap'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :demo do
  gem 'puma'
  gem 'listen'
end
