source 'https://rubygems.org'

# lib needs these at run-time
gem 'json'
gem 'nokogiri'
gem 'rake'
gem 'ruby-ldap'
gem 'wunderbar'
gem 'pdf-reader'

# For Travis testing
group :test do
  gem 'rspec'
  # gem 'whimsy-asf', path: File.expand_path('..', __dir__)
end
