source 'https://rubygems.org'

gem 'rake'
gem 'ruby-ldap'
gem 'wunderbar'
gem 'ruby2js'
gem 'sinatra', '~> 2.0'
gem 'nokogumbo'
gem 'mail'
gem 'kramdown'
gem 'sanitize'

group :development do
  gem 'passenger'
  gem 'listen'
end
